[package]
name = "termdraw"
version = "0.1.6"
edition = "2021"
authors = ["spiel0meister"]
description = "A crate, which allows you to draw in the terminal."
license = "MIT"
repository = "https://github.com/spiel0meister/termdraw"

[dependencies]
crossterm = "0.27.0"
